name : smoke-as-tib

on: 
  push: 
  schedule:
    - cron: '1 1 * * *'

jobs:
  perl:

    runs-on: ubuntu-latest

    steps:
      - name: Smoke
        run: docker run tibtibdocker/perl-smoker-tib

