name : perl-blead

on: 
  push: 

jobs:
  perl:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: docker build
        run: docker build -t tibtibdocker/perl-smoker-root .
      - name: docker login
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: docker push
        run: docker push tibtibdocker/perl-smoker-root
