name : smoke-as-root

on: 
  push: 
  schedule:
    - cron: '0 0 * * *'

jobs:
  perl:

    runs-on: ubuntu-18.04

    steps:
      - name: Smoke
        run: docker run tibtibdocker/perl-smoker-root
