name : smoke-root

on: 
  push: 
  schedule:
    - cron: '* * */1 * *'

jobs:
  perl:

    runs-on: ubuntu-latest

    steps:
      - name: Smoke
        run: docker run tibtibdocker/perl-smoker-root
