name : smoker-tib

on: 
  push: 

jobs:
  perl:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: docker build -f Dockerfile_tib
        run: docker build -t tibtibdocker/perl-smoker-tib .
      - name: docker login
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: docker push
        run: docker push tibtibdocker/perl-smoker-tib
